spring.application.name=EchoSync

# ??????? (?????? 3306 ??)
spring.datasource.url=jdbc:mysql://localhost:3306/echosync?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? MyBatis-Plus ???? SQL ???????????????????
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
